"""
Time-aware train/test split for time-series data.
No shuffling - split by unit_nr: first 80% of machines for training, last 20% for testing.
"""

import joblib
import pandas as pd
from pathlib import Path


def create_time_aware_split(features_df_path='data/features_df.pkl', output_dir='data'):
    """
    Create time-aware train/test split for time-series data.
    
    Args:
        features_df_path: Path to the features DataFrame pickle file
        output_dir: Output directory to save train/test splits
    
    Returns:
        tuple: (X_train, y_train, X_test, y_test, train_units, test_units)
    """
    
    # Load the features dataframe
    df = joblib.load(features_df_path)
    print(f"Loaded features dataframe: {df.shape}")
    print(f"Columns: {df.columns.tolist()}")
    print(f"Data types:\n{df.dtypes}\n")
    
    # Get unique units in order (time-aware, no shuffling)
    units = df['unit_nr'].unique()
    print(f"Total units: {len(units)}")
    print(f"Unit IDs (first 10): {units[:10]}")
    
    # Split: first 80% for training, last 20% for testing
    split_idx = int(len(units) * 0.8)
    train_units = units[:split_idx]
    test_units = units[split_idx:]
    
    print(f"\nTrain units: {len(train_units)} machines")
    print(f"Test units: {len(test_units)} machines")
    
    # Create train and test dataframes
    train = df[df['unit_nr'].isin(train_units)]
    test = df[df['unit_nr'].isin(test_units)]
    
    print(f"\nTrain set: {train.shape}")
    print(f"Test set: {test.shape}")
    
    # Drop unnecessary columns
    drop_cols = ['unit_nr', 'time_cycles', 'max_cycles', 'RUL', 'failure']
    # Only drop columns that exist
    drop_cols = [col for col in drop_cols if col in df.columns]
    
    X_train = train.drop(columns=drop_cols)
    y_train = train['failure'] if 'failure' in train.columns else None
    
    X_test = test.drop(columns=drop_cols)
    y_test = test['failure'] if 'failure' in test.columns else None
    
    print(f"\nX_train shape: {X_train.shape}")
    print(f"X_test shape: {X_test.shape}")
    
    if y_train is not None:
        print(f"y_train shape: {y_train.shape}")
        print(f"y_test shape: {y_test.shape}")
        print(f"\nClass distribution (train):")
        print(y_train.value_counts())
        print(f"\nClass distribution (test):")
        print(y_test.value_counts())
    
    # Save the splits
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    
    joblib.dump(X_train, f'{output_dir}/X_train.pkl')
    joblib.dump(X_test, f'{output_dir}/X_test.pkl')
    
    if y_train is not None:
        joblib.dump(y_train, f'{output_dir}/y_train.pkl')
        joblib.dump(y_test, f'{output_dir}/y_test.pkl')
    
    # Save metadata
    metadata = {
        'train_units': train_units.tolist(),
        'test_units': test_units.tolist(),
        'train_samples': len(train),
        'test_samples': len(test),
        'n_features': X_train.shape[1],
        'feature_names': X_train.columns.tolist()
    }
    joblib.dump(metadata, f'{output_dir}/split_metadata.pkl')
    
    print(f"\nTrain/test split saved to {output_dir}/")
    print(f"  - X_train.pkl: {X_train.shape}")
    print(f"  - X_test.pkl: {X_test.shape}")
    if y_train is not None:
        print(f"  - y_train.pkl: {y_train.shape}")
        print(f"  - y_test.pkl: {y_test.shape}")
    print(f"  - split_metadata.pkl: metadata")
    
    return X_train, y_train, X_test, y_test, train_units, test_units


if __name__ == '__main__':
    try:
        X_train, y_train, X_test, y_test, train_units, test_units = create_time_aware_split()
    except FileNotFoundError as e:
        print(f"ERROR: {e}")
        print("\nNote: features_df.pkl not found. Run feature engineering first.")
        print("The features_df.pkl should be generated by the feature engineering pipeline.")
